<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderDetailTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('order_details')->truncate();
        DB::table('order_details')->insert([
            [
                'order_id'=>983,
                'product_id'=>109,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>998,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>498,
                'product_id'=>105,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>847,
                'product_id'=>110,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>305,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>309,
                'product_id'=>107,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>983,
                'product_id'=>106,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>827,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>309,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>847,
                'product_id'=>108,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>983,
                'product_id'=>109,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>998,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>498,
                'product_id'=>105,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>847,
                'product_id'=>110,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>305,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>309,
                'product_id'=>107,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>983,
                'product_id'=>106,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>827,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>309,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>847,
                'product_id'=>108,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>983,
                'product_id'=>109,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>998,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>498,
                'product_id'=>105,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>847,
                'product_id'=>110,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>305,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>309,
                'product_id'=>107,
                'quantity'=>'',
                'amount'=>1,
            ],
            [
                'order_id'=>983,
                'product_id'=>106,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>827,
                'product_id'=>102,
                'quantity'=>'',
                'amount'=>2,
            ],
            [
                'order_id'=>309,
                'product_id'=>101,
                'quantity'=>'',
                'amount'=>4,
            ],
            [
                'order_id'=>847,
                'product_id'=>108,
                'quantity'=>'',
                'amount'=>1,
            ]
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
